### ISSUE TITLE
Add sorting button to all compatible lists

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#113]
4.7 inch phone. 
4.5.2. Beta

Also not in the menu with the three dots

**Comment by Invictaz** [comment]
![Screenshot_20210614-210316_Unchained](https://user-images.githubusercontent.com/20338545/121945265-de455f00-cd53-11eb-8120-e1f9dc33e9c7.jpg)

**Comment by LivingWithHippos** [comment]
Sorting  menu is in folders only (when you download a folder link or click on a torrent with multiple files). I'll have to try and port it to these lists

**Comment by Invictaz** [comment]
Would be welcome to have sorting in these lists as well.

**Comment by LivingWithHippos** [comment]
at the moment it's not possible to directly sort the downloads and torrent lists, I'm going to put the issue on hold.
Sorting has been added to the search list

**Comment by LivingWithHippos** [comment]
closing for #243, still no easy way to do this for now
