### ISSUE TITLE
No option to download all files in container

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#115]
Container attacted, unzip this first to get the .dlc file

[724e8fdef668731aac0d6549c5ffb48cb2e025a2.zip](https://github.com/LivingWithHippos/unchained-android/files/6650807/724e8fdef668731aac0d6549c5ffb48cb2e025a2.zip)

![Screenshot_20210614-213624_Unchained](https://user-images.githubusercontent.com/20338545/121948989-3e3e0480-cd58-11eb-9dc7-8f5298cb442e.jpg)

**Comment by Invictaz** [comment]
Some text is being cut off as well as you can see in the screenshot

**Comment by LivingWithHippos** [comment]
> Some text is being cut off as well as you can see in the screenshot

you mean the text on the bottom?

**Comment by Invictaz** [comment]
I mean the DTS-HD.MA

It used to be this so a lot is cut of. It ends with .rar

![Screenshot_20210614-215741_Unchained](https://user-images.githubusercontent.com/20338545/121951418-2fa51c80-cd5b-11eb-8dda-2a45855ecbd0.jpg)

**Comment by LivingWithHippos** [comment]
yes I didnt want to have huge cards so I limited the title to three rows. I could split it in the middle instead of letting it split at the end or just let the cards be as tall as they wanted, they'd just be uneven.

**Comment by Invictaz** [comment]
Smaller font?
