### ISSUE TITLE
Download button for a torrent that is already downloading 

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#117]
Torrent is already downloading (at 36% progression) but long press on it still gives a button to download it? Why?

Better would be a button to stop the download (since pause is not possible?) or something else.

![Screenshot_20210614-225240_Unchained](https://user-images.githubusercontent.com/20338545/121961063-36d22780-cd67-11eb-9ec0-6973fee74feb.jpg)

**Comment by LivingWithHippos** [comment]
That is just the status for the torrent on the real debrid servers, the one you get going into the torrent section of real debrid. The download button asks real debrid to transform it into a download. Only removal is possibile. I suppose I could try to remove the download option if the torrent is not in the downloaded status

**Comment by Invictaz** [comment]
Or, of it is downloaded, make it into a button that says download to phone or something
