### ISSUE TITLE
Download list is empty after going back from info page

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#118]
After you go back from the information page (with the kodi button) there is a bug sometimes and the list is empty. Only option is to restart the app.

**Comment by Invictaz** [comment]
![Screenshot_20210617-003527_Unchained](https://user-images.githubusercontent.com/20338545/122303484-eb08b500-cf03-11eb-9ba0-0c5290810ffc.jpg)

**Comment by Invictaz** [comment]
Pressing the buttons in the purple bar below is not possible.
Only option is to restart the app.

My download list contains over 500 titles.

**Comment by LivingWithHippos** [comment]
Mmh the bottom bar usually gets deactivated when there is a login issue, are you using the private api key or the normal login flow?

**Comment by Invictaz** [comment]
Private API key. No warning messages.

**Comment by LivingWithHippos** [comment]
Do you have issues with your internet? Could it be that you lost connection for a minute?

**Comment by Invictaz** [comment]
I does happen often. I suspect it has nothing to do with the internet.

**Comment by LivingWithHippos** [comment]
may have been fixed with 1a8ff75b73b1a06c403aa2a441b290142f30e404 (version 4.33.12), needs to be tested
