### ISSUE TITLE
[FEATURE REQUEST] No option to restart failed magnet

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#124]
Not sure if this is a feature request or a bug.

The Magnet fails. There is no way to restart or retry it. 

![Screenshot_20210630-142027_Unchained](https://user-images.githubusercontent.com/20338545/123968582-a37c3180-d9b7-11eb-8660-fc731c4f5489.jpg)

**Comment by LivingWithHippos** [comment]
Try using the same magnet on the real debrid web interface. Restarting is not possible so if it gives an error on the website too there's nothing I can do. It could be because there are no seeds or because the magnet is malformed.

**Comment by LivingWithHippos** [comment]
If you paste the magnet on real debrid it will show you
```
Your magnet can not be downloaded, possible reasons:
- No seeders are available
- The torrent file sent by seeders is invalid or corrupted
```

**Comment by Invictaz** [comment]
There is no option to export the Torrent. I got it via the search I think, not sure.

**Comment by LivingWithHippos** [comment]
Sorry these errors are on real debrid side, not one mine so I can't add any details aside from those they give me.

The downloads can't be restarted since real debrid does not allow it, and even if we could it would probably give an error again. It may be that it just has 0 seeders.
