### ISSUE TITLE
[BUG] app crash when you search something with magnetdl

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#128]
**Describe the bug**
Use magnetdl as your search provider, type in "harry potter" or something, click search. The app will crash

**Smartphone (please complete the following information):**
 - Device: pixel 4a
 - OS: android 12 beta 2.1

**Comment by LivingWithHippos** [comment]
There is a bugfix for using magnetdl in github but not on the releases. Are you using the play store/github releases maybe?

**Comment by oathzed** [comment]
Oh yeah I was using the latest release from GitHub :).

Thanks, all working now, I'll close this issue
