### ISSUE TITLE
[FEATURE REQUEST] Sort option for search

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#132]
Add a sort option button for, seeds, file size, a to z.

Not sure if this is a duplicate of:

https://github.com/LivingWithHippos/unchained-android/issues/113

Or it's different enough

![Screenshot_20210704-083820~2](https://user-images.githubusercontent.com/52545913/124391296-c69f2d80-dca4-11eb-929f-b6c823f6093d.png)

**Comment by LivingWithHippos** [comment]
Let's keep the other one

**Comment by oathzed** [comment]
Ok got yeh :)
