### ISSUE TITLE
[BUG] Opening torrent file with unchained doesn't upload file to RD

### ISSUE THREAD

**Issue by nine76evil** [LivingWithHippos/unchained-android#139]
1. Click on torrent file to open
2. Select open with unchained
3. Unchained opens to New Download tab
4. Torrent doesn't upload as expected

 - Device: Pixel 3a
 - OS: Android 11

- App Version: 4.16-4 beta

**Comment by LivingWithHippos** [comment]
Hello and thanks for the feedback.

I've just tried it and it works for me, maybe the torrent is malformed, can you try it with another torrent downloader? Or just the real debrid website.

When it goes to new download, do you get any message? Do the buttons get greyed out?

**Comment by nine76evil** [comment]
Okay the issue seems to be when loading the torrent file from Firefox so it's a browser downloader issue. I'll troubleshoot from there and close the bug. Odd though once I opened the torrent file using amaze file manager and unchained it loaded but all my torrents on RD disappeared.

Sent from ProtonMail mobile

-------- Original Message --------
