### ISSUE TITLE
update the navigation libraries

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#144]
The bottom navbar with multiple stacks is now supported directly without all the extra code that is used right now.

See the [official sample](https://github.com/android/architecture-components-samples/blob/main/NavigationAdvancedSample/app/src/main/java/com/example/android/navigationadvancedsample/MainActivity.kt) and adapt it

EDIT: at the moment it does not seem to work. Waiting for a stabler version. Latest tried with alpha09. See the [consolidate-navigation branch](https://github.com/LivingWithHippos/unchained-android/tree/consolidate-navigation)

**Comment by Invictaz** [comment]
Isnt this only in certain Android versions and up?

**Comment by LivingWithHippos** [comment]
No, I'm already using this library in the app it just got updated to integrate the backstack on every tab feature. I'll be able to remove [this file](https://github.com/LivingWithHippos/unchained-android/blob/master/app/app/src/main/java/com/github/livingwithhippos/unchained/utilities/extension/NavigationExtension.kt) and others

**Comment by LivingWithHippos** [comment]
will be closed by ec7445f89c396aa6a4cc7569a4fa5b3173e3f7d1
