### ISSUE TITLE
[DISCUSSION] Change the app name/icon to better reflect its uses

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#145]
It's been suggested to me that the icon and app name do not reflect its uses (a real debrid manager/ downloader)

I guess changing the name to "Unchained for Real Debrid" shouldn't be too much of a problem. As for the icon I just like it.

**Comment by Invictaz** [comment]
If you take on the name RD which is a trademark you might get in trouble. I would say leave it as it is.

**Comment by LivingWithHippos** [comment]
keeping the name for now
