### ISSUE TITLE
[FEATURE REQUEST] Change download folder in settings

### ISSUE THREAD

**Issue by SeedTrain** [LivingWithHippos/unchained-android#146]
It would be nice to add a setting where you can change the download folder in the settings to auto download to that folder or when you find a link, I click the share button and open it up in app, it would be nice to select a certain folder

**Comment by LivingWithHippos** [comment]
Hello and thanks for the feedback, for the download folder you can follow issue #105, I can't  understand what do you mean with

> when you find a link, I click the share button and open it up in app, it would be nice to select a certain folder

can you give me more details?

**Comment by SeedTrain** [comment]
> Hello and thanks for the feedback, for the download folder you can follow issue #105, I can't understand what do you mean with
> 
> > when you find a link, I click the share button and open it up in app, it would be nice to select a certain folder
> 
> can you give me more details?

So when I download something from mobilism for example, I click the download link, hit the share button and opens up Unchained and it would be nice for that link to be selected where you want to download that file to. I'm sorry I'm having a hard time explaining it.

**Comment by LivingWithHippos** [comment]
ok if I understand correctly you want to download a first file somewhere, and when you share a second link to real debrid you want that first file location to be ready when you press download again, right?

**Comment by LivingWithHippos** [comment]
if you set up the new okhttp downloader in settings this should work
