### ISSUE TITLE
Add app to F-Droid

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#15]
Check ["Submitting to F-Droid Quick Start Guide"](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) and ["Contributing to F-Droid"](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests)

**Comment by Invictaz** [comment]
Don't forget other app stores like Amazon and Aptoide

**Comment by LivingWithHippos** [comment]
closed with 1a8ff75b73b1a06c403aa2a441b290142f30e404
