### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cheddartoast** [LivingWithHippos/unchained-android#153]
When selecting the plugins in X-plore (or any file manager application), it opens Unchained but says "Plugin not installed". I've tried multiple times with the different plugins. ![Screenshot_2021-08-07-01-01-10-541_com.github.livingwithhippos.unchained.jpg](https://user-images.githubusercontent.com/88544266/128578586-4ffb000b-4850-44d6-bd8a-3b29c2744af9.jpg)

Phone model: Xiaomi Mi10t pro, latest firmware.

**Comment by LivingWithHippos** [comment]
Yes it's my bad, I updated the plugins for a new version but I need to release it yet.

You can either:


- use the plugins from this older page: https://github.com/LivingWithHippos/unchained-android/tree/use-sort-filters/extra_assets%2Fplugins to share links like https://github.com/LivingWithHippos/unchained-android/blob/use-sort-filters/extra_assets/plugins/1337.unchained

- wait for the new app version

- install the app from the nightly version  of github (may be bugged, has the new search plugins)

- install the latest app from the release page of github: https://github.com/LivingWithHippos/unchained-android/releases/tag/4.16.4-beta (they should include the plugins)

**Comment by LivingWithHippos** [comment]
Should be fixed with the new release  (out now on github, on google play in the next few days)
