### ISSUE TITLE
[FEATURE REQUEST] Optimize the app for big screens

### ISSUE THREAD

**Issue by Mav3r1x** [LivingWithHippos/unchained-android#164]
Hi Dev,

The app is already pretty easy to use on tablets. I was thinking that moving the bottom navigation bar to the left side on tablets/chromeOS would be better. I got the idea from Google Photos' similar implementation. Thanks.

**Comment by LivingWithHippos** [comment]
Interesting. Some info [here](https://material.io/components/bottom-navigation#behavior) under the "Scaling and adaptation" section. They say to use a navigation rail on medium screens and a navigation drawer on big screens. 

Navigation is tightly coupled with this app so changing it could be a bit of work but it should be doable. I think that using a navigation rail for everything could be faster, they say not to use it on small screens but what do they know, they literally have [a pic](https://lh3.googleusercontent.com/Hto0ydzBZ5iPJS9ZSt0PIsjSoY6qmgLBg10QFp2wa5OfeTrlar9IK2i_-tTYcMhdvs3g1U1L3k0tjTIBsPDJZqL7xPO5Nh1LXoeb-A=w1064-v0) of it being used on a phone in its article ;D

[navigation rail](https://material.io/components/navigation-rail)

[navigation drawer](https://material.io/components/navigation-drawer)

This will definitely need to wait for #144 to be finished first

**Comment by Mav3r1x** [comment]
I agree that using navigation rail makes sense. I don't why it is not recommended for small screen size; Google's own apps use it. Probably small screen size does not refer to phones, not sure.
But glad to know that you will work on this.

**Comment by LivingWithHippos** [comment]
closed in favour of more specific issues since a lot of changes have been made to make the app usable on tvs
