### ISSUE TITLE
[FEATURE REQUEST] Hold Down multiple and do copy urls

### ISSUE THREAD

**Issue by redx113** [LivingWithHippos/unchained-android#178]
Say if we are on the torrent list or inside a season pack. If we hold down and select say 20 of them, make an option to copy all urls from there, like we can do currently for one file. That would be an awesome game changer to make it easy to copy and than be able to paste those urls in download manager in windows like IDM.

I hope this will be an easy and possible add. Thanks!!

**Comment by LivingWithHippos** [comment]
I have added a copy all items in the next version (for #157), would a copy of only the selected items be useful too?

**Comment by redx113** [comment]
Hi,

First I want to thank you so much for making such an amazing program to manage torrents on real-debrid. Also, thanks for getting back to me so fast! The selected items only would be useful too if on the main torrents page and hold down and select 20 from there but all spaced out, that is good example of the copy all urls for.

I thank you so much again for such an amazing app and for replying so quickly!
> I have added a copy all items in the next version (for #157), would a copy of only the selected items be useful too?

**Comment by Invictaz** [comment]
Agree with the multiple selection
