### ISSUE TITLE
[BUG] DoH nag repetition

### ISSUE THREAD

**Issue by morpheasgr** [LivingWithHippos/unchained-android#184]
Version: 4.27.5beta GPlay

DNS over HTTPS nag does not appear just once, but every single time I open the "Search" tab. While I am a fan of DoH/DoT, Google's DNS is not my cup of tea so I will not enable it, I either use Cloudflare or Quad9, but I do so device-wide/network-wide.

To reproduce: Fresh install, authenticate, open Search tab, hit Disable on DoH nag, next time you open the search tab it should reappear. If it doesn't reappear the first time it should happen the second.

Expected behaviour: a single one-time warning should suffice, imho. Labeled this as a bug in case it is one.

Temporary workaround: Enabling and then disabling the DoH feature once seems to take care of the issue/bug.

Thanks once again for your dedication and the high quality you always deliver on this project.

PS: I wish I could port Unchained to Windows and use it to associate magnet links and torrent files with it. There's no real alternative to your app on desktop, might mess around with Windows 11's "Windows Subsystem for Android" to see if Windows can use Android apps to handle certain protocols or filetypes.

**Comment by LivingWithHippos** [comment]
Ok I can reproduce the bug, it should be easy to fix.

>  I either use Cloudflare or Quad9, but I do so device-wide/network-wide.

I'll try to also add those in the future

>I wish I could port Unchained to Windows and use it to associate magnet links and torrent files with it. There's no real 
> alternative to your app on desktop, might mess around with Windows 11's "Windows Subsystem for Android" to see if 
> Windows can use Android apps to handle certain protocols or filetypes.

There is a firefox plugin that should help you, but I'm not sure if it's mantained anymore.

**Comment by morpheasgr** [comment]
> There is a firefox plugin that should help you, but I'm not sure if it's mantained anymore.

@LivingWithHippos 

As long as it is working I will be happy. I was searching for an RD firefox plug-in actually, I only found the official one but it didplays a blank frame for me. There is a Chrome plug-in (RDDM), but I was under the impression that it is unsafe for some reason. Got some weird Google search results while I had it installed.
