### ISSUE TITLE
[BUG] App stuck on loading forever

### ISSUE THREAD

**Issue by hackel** [LivingWithHippos/unchained-android#188]
**Describe the bug**
Had previously signed in to Unchained and everything was working well.  Opened it today, and all I get is the loading spinner.  I can open settings, but bottom buttons do nothing.

**Screenshots**
![Screenshot_20220115-220432.png](https://user-images.githubusercontent.com/583677/149646871-ae4ca594-2a8a-4eb2-bfb0-6a09a1351df6.png)

**Smartphone:**
 - Device: Pixel 4a
 - OS: Android 12, Jan update

**Additional context**
- App Version: 4.27.2-beta (F-droid)

I also use NetGuard and can see Unchained *is* connecting to api.real-debrid.com when I open it.  Perhaps they released a new API version?

**Comment by LivingWithHippos** [comment]
Thanks for the feedback. The quickest fix I can suggest you is to delete the app data and login again. 

The reason this bug happens could be any of the following :

- Real debrid servers down
- Your network is down
- You are using with a vpn
- there is a bug in the login Flow

I'll try to add a clearer way to find out the reason, sadly for this particular bug I need to debug on my own device

**Comment by LivingWithHippos** [comment]
may have been fixed with 1a8ff75b73b1a06c403aa2a441b290142f30e404 (version 4.33.12), needs to be tested
