### ISSUE TITLE
[FEATURE REQUEST] add web video cast as player

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#199]
**Is your feature request related to a problem? Would be good to have web video cast as player, so you can Chromecast to different devices. https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo

**Describe the solution you'd like**
ability to cast to different devices

**Describe alternatives you've considered**
Built in Chromecast, although it doesn't support as many codecs.

**Additional context**
https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo

Documentation:

http://www.webvideocaster.com/integrations

**Comment by Invictaz** [comment]
Better choose BubbleUPnP. It supports transcoding in the premium version which supports much more codecs.

**Comment by oathzed** [comment]
> Better choose BubbleUPnP. It supports transcoding in the premium version which supports much more codecs.

I've actually had better luck with web video cast

**Comment by Invictaz** [comment]
> > Better choose BubbleUPnP. It supports transcoding in the premium version which supports much more codecs.
> 
> I've actually had better luck with web video cast
> 
> Web video cast can cast to way more device types.

If you use the web receiver indeed. But the lack of codec support seriously hampers it. It's like Localcast which almost always doesn't work because of the lack of codecs. For simple MP4 with AAC it works but for EAC3 (Dolby) and other exotics it simply does not render at al.

**Comment by oathzed** [comment]
> > > Better choose BubbleUPnP. It supports transcoding in the premium version which supports much more codecs.
> > 
> > 
> > I've actually had better luck with web video cast
> > Web video cast can cast to way more device types.
> 
> If you use the web receiver indeed. But the lack of codec support seriously hampers it. It's like Localcast which almost always doesn't work because of the lack of codecs. For simple MP4 with AAC it works but for EAC3 (Dolby) and other exotics it simply does not render at al.

I'll check it out, but it doesn't mean we can't have both. Also web video cast has a built in web browser so that's also useful for stuff outside of unchained

**Comment by Invictaz** [comment]
> > > > Better choose BubbleUPnP. It supports transcoding in the premium version which supports much more codecs.
> > > 
> > > 
> > > I've actually had better luck with web video cast
> > > Web video cast can cast to way more device types.
> > 
> > 
> > If you use the web receiver indeed. But the lack of codec support seriously hampers it. It's like Localcast which almost always doesn't work because of the lack of codecs. For simple MP4 with AAC it works but for EAC3 (Dolby) and other exotics it simply does not render at al.
> 
> I'll check it out, but it doesn't mean we can't have both. Also web video cast has a built in web browser so that's also useful for stuff outside of unchained

I'm not sure I understand why you need the webbrowser?

**Comment by oathzed** [comment]
> 

Unrelated to unchained, it's good to cast any video types.
