### ISSUE TITLE
[FEATURE REQUEST] Download button does not show location chooser

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#202]
If you press on the download button, it only is able to download to internal storage. There is no location chooser to download to external micro SD or other folders. 

![Screenshot_20220422-234205_Unchained](https://user-images.githubusercontent.com/20338545/164799548-677893a3-7812-4af5-b437-c7b3cdb31ada.jpg)

**Comment by LivingWithHippos** [comment]
duplicate of #105

**Comment by Invictaz** [comment]
Not a duplicate. Location chooser can also point to a specific location on the internal SD card.

**Comment by LivingWithHippos** [comment]
Right now the downloader uses the internal memory because the default Android downloader allows only that (unless I've been missing something). When I implement the download on sd card stuff I'll allow downloading on any folder, not just on the external sd
