### ISSUE TITLE
[BUG] Scene-Rls does not render correctly

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#203]
Scene-rls does only render a link as result not the individual download links to episodes. Clicking on this opens the browser. 

![Screenshot_20220423-004908_Unchained](https://user-images.githubusercontent.com/20338545/164814537-457ffbf5-8c2d-4c6d-9cc2-ddc80c33244f.jpg)

**Comment by LivingWithHippos** [comment]
That specific page does not have link to the hosters, they point to other pages that also have a link protection
