### ISSUE TITLE
[FEATURE REQUEST] Add opening handlers to supported holsters

### ISSUE THREAD

**Issue by yolorag** [LivingWithHippos/unchained-android#207]
I do t know how exactly it's called when it comes to programming so forgive me if I got it wrong.
What I mean is that when opening for example Rapidgator.net link in another app, there should be an option to open it in Unchained. This part of the list from official Real Debrid app  

https://imgur.com/a/T9ij5F6

**Comment by Invictaz** [comment]
Problem is that these links dont have a suffix like .torrent so it's going to be hard.
