### ISSUE TITLE
[BUG] Activity does not recover after getting destroyed

### ISSUE THREAD

**Issue by eazymo** [LivingWithHippos/unchained-android#208]
I am logged in with my apitoken. Using my phone to watch my content and everything plays fine.

**Bug
Downloads and search cant be clicked after launching MX player or kodi to play a torrent.
I am stuck on user page. I have to close Unchained and relaunch it to be able to navigate to downloads and search again.

**Steps to reproduce the behavior:
1. Go to downloads
2. Click on a torrent you want to play
3. Launch torrent with kodi or MX player
4. Let video play. after it plays.
5. Go back to unchained 
6. Bug: can't click on downloads and search. stuck on user page.

**
 - Device: P30 Pro Huawei
 - OS: Android 10/EMUI 12
**
- App Version: 4.33.10-beta , source github

I also had this problem with play store version 4.27.5-beta. that's why I downloaded github version but it has the same bug.

**Comment by LivingWithHippos** [comment]
Ok i know more or less where to look, anyway yes I didn't fix it with the new release on github

**Comment by eazymo** [comment]
it does get annoying after a while but besides that it works great. I will wait for an update no rush!

**Comment by LivingWithHippos** [comment]
closed with 1a8ff75b73b1a06c403aa2a441b290142f30e404

**Comment by LivingWithHippos** [comment]
wrong issue

**Comment by LivingWithHippos** [comment]
may have been fixed with 1a8ff75b73b1a06c403aa2a441b290142f30e404 (version 4.33.12), needs to be tested

**Comment by eazymo** [comment]
is issue is still present tried both versions: v4.33.12 and v4.35.0
only fix is closing the app and restarting it.

**Comment by LivingWithHippos** [comment]
Thanks for trying, I'll need to simulate this situation on my own, the emulator should have an option to simulate low memory situations. How much time after you play the video does this happen?

**Comment by eazymo** [comment]
when i play a file with mx player and close it instantly the app works as normal but if i let the video play a few seconds longer it stays stuck on user page.

**Comment by eazymo** [comment]
here is the video for reference:
https://imgur.com/a/qbRIUZ9

**Comment by eazymo** [comment]
disabling auto-rotate function keeps the unchained app working as it should.

**Comment by LivingWithHippos** [comment]
I just fixed the issue and will release the fix soon, if you re in a hurry you can try one of the latest apk in the Actions section [like this](https://github.com/LivingWithHippos/unchained-android/actions/runs/2456395035)

**Comment by Invictaz** [comment]
@LivingWithHippos  Maybe this was the issue with #118 that I rotated my phone and therefore the list was empty.
