### ISSUE TITLE
[BUG] duplicate providers

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#229]
**Describe the bug**
Providers get duplicated 

**To Reproduce**
1. Go to install providers
2. Delete them from settings
3. Restart app, then install them again, restart again
4. Youll see duplicates of all them

**Screenshots**
https://imgur.com/a/1zaIbsK

**Smartphone (please complete the following information):**
 - Device: pixel 4a
 - OS: android 12.1

**Additional context**
4.40.2-beta

**Comment by LivingWithHippos** [comment]
should not be an issue anymore with the new plugin repository structure
