### ISSUE TITLE
Ability to delete files!

### ISSUE THREAD

**Issue by Cueball666uk** [LivingWithHippos/unchained-android#23]
Hi, just tried your app and it's so much cleaner than the "real" real debrid app. I would love the ability to delete from my account from within your app. Great work thank you so much

**Comment by LivingWithHippos** [comment]
Thanks for the feedback, it should not be too hard

**Comment by Cueball666uk** [comment]
This would just seal the deal. As the real debrid app does not even give
this option !

Is there a way we can donate?

**Comment by LivingWithHippos** [comment]
> Is there a way we can donate?

Too kind, I have [a donation section in the README](https://github.com/LivingWithHippos/unchained-android#donate-coffee) ;D

Can I ask you if you wanted to delete from the download details page or the download list page or both?

**Comment by Cueball666uk** [comment]
Both would be good, as sometimes you realise to late that downloads are
going to take too long or have got stuck. Also if I've finished with a file
or helps to keep my list clean! 👍🏻🙂

**Comment by LivingWithHippos** [comment]
> sometimes you realise to late that downloads are going to take too long or have got stuck

Well Unchained has no integrated download manager (aside for downloading the .torrent file when you share a link like https://torrents.linuxmint.com/torrents/linuxmint-17-cinnamon-32bit-v2.iso.torrent with it), you need to interrupt the download by itself. Maybe you meant the torrent download? That can be implemented

> Also if I've finished with a file or helps to keep my list clean

this can be done

**Comment by Cueball666uk** [comment]
Yes you are correct ... What I meant was the ability to delete anything
from the torrent list..

**Comment by LivingWithHippos** [comment]
You can check the .apk to test it [at circleci.](https://app.circleci.com/pipelines/github/LivingWithHippos/unchained-android/307/workflows/6b685739-db67-4088-b2cb-04fa9cae039a/jobs/307/artifacts) I'm not 100% sure you can access this, so tell me if there are any problems (I think you need to be logged in).

**Comment by Cueball666uk** [comment]
WOW..! That's amazing and exactly what I needed. Thank you so much and so
quick too !

Truly appreciate it! This addition makes the official real-debrid app
useless to me now. Amazing work !

**Comment by LivingWithHippos** [comment]
Yes it's "normal" because it expires every hour and it does not get renewed automatically because I haven't yet implemented a management of api errors. You can folllow issue #22 (the pinned one). I'm working on it right now so it shold be solved today/tomorrow.

**Comment by LivingWithHippos** [comment]
I fixed the hourly logout in 1.6.7 beta. Google should publish an update at worst tomorrow if you don't use the Github release.

**Comment by Cueball666uk** [comment]
You are really quick at solving these issues, bravo and great work.

I have another query if I try and share a downloadable link from another
app and "share with" unchained, I notice unchained opens to the user page
and the download is not initiated... I have to actually copy the link and
then paste into the link box for unchained to recognise and download the
link.
