### ISSUE TITLE
[FEATURE REQUEST] An option to select multiple torrents for transferring to the RD account. 

### ISSUE THREAD

**Issue by ShebeerPrince** [LivingWithHippos/unchained-android#232]
This would be very useful. Now we have to try torrents one by one to know whether it is cached or not. If not cached, we have to come back and try another torrent from the search result. This cycle continues. 

Adding an option to select multiple torrents at a time from the **_search result_** for transferring to the RD account will make it easy since the chances of getting a pre cached torrent is high.

**Comment by LivingWithHippos** [comment]
Are you talking about the search screen?

**Comment by ShebeerPrince** [comment]
> Are you talking about the search screen?

Yes exactly. From the search result tab, an option to select multiple files and add those to RD, so that we don't have to come back to the result page and try another torrent when the first one is not cached or is slowly caching. 

I have no idea whether it is possible or not, just discussing it. Thanks for this wonderful app.

**Comment by LivingWithHippos** [comment]
Yeah it's doable but It will required some work because torrents needs to get their file selected "actively" compared with holsters which can be just downloaded.

Anyway there is another issue that will add a caching indicator to the search results

**Comment by ShebeerPrince** [comment]
> Yeah it's doable but It will required some work because torrents needs to get their file selected "actively" compared with holsters which can be just downloaded.
> 
> Anyway there is another issue that will add a caching indicator to the search results

That is more than enough my friend. A caching status indicator in the search result would suffice. Thank you.
