### ISSUE TITLE
[BUG] rlsbb provider seems to be not working/side bug

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#236]
**Describe the bug**
The rlsbb providers doesn't work.
Also side bug with search

**To Reproduce**
1. Go to search tab, and use scene-rls provider
2. Now search for "interior design masters"
3. Wait till results show, then switch it to rlsbb providers, and press search with the same text in the search field.
4.  It will keep the results from scene-rls and fail search.
5. If the provider/search fails, it should clear those results from another provider.

**Smartphone (please complete the following information):**
 - Device: Google pixel 4a
 - OS: android 12.1

**Additional context**
- App Version: 4.40.2-beta

**Comment by LivingWithHippos** [comment]
rlsbb may have adedd cloudflare protection so I think I'll remove it, see https://github.com/LivingWithHippos/unchained-android/discussions/213

> If the provider/search fails, it should clear those results from another provider.

yes

**Comment by oathzed** [comment]
> rlsbb may have adedd cloudflare protection so I think I'll remove it, see #213
> 
> > If the provider/search fails, it should clear those results from another provider.
> 
> yes

Aww dang, ok. That makes sense. Thanks man

**Comment by LivingWithHippos** [comment]
fixed with 67a70a94

**Comment by oathzed** [comment]
Rlsbb seems to not be working again :(

**Comment by LivingWithHippos** [comment]
> Rlsbb seems to not be working again :(

they changed the page path, an update for the plugin should be now available

**Comment by oathzed** [comment]
> > Rlsbb seems to not be working again :(
> 
> they changed the page path, an update for the plugin should be now available

Awesome. Working great now, thanks for the speedy fix man!
