### ISSUE TITLE
{Request] Add "Open with" option

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#24]
So you can open a streaming link with apps like Yatse: https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree to send the video file straight to Kodi

**Comment by LivingWithHippos** [comment]
Sounds good, I'll add it to the Download Details Fragment

**Comment by oathzed** [comment]
> Sounds good, I'll add it to the Download Details Fragment

Awesome :]

**Comment by oathzed** [comment]
@LivingWithHippos Also might want to check out this project, imagine if you could search anything you wanted inside Unchained and add it to your real debrid or just stream it directly. https://github.com/wako-unofficial-addons/helios Its addon based, so you can add your own providers

**Comment by LivingWithHippos** [comment]
I thought about it (I know qBittorrent also has a nice plugin system), but I have some issues:

- I don't want to risk it getting kicked out of the Play Store
- It would require to develop and maintain the plugins 
- It would change the app from being an interface for Real Debrid to be (also) something else -> you could use a specialized app for that, in the end it would just be a couple of taps away

So let's just say that it is in the plans ;D

**Comment by oathzed** [comment]
> I thought about it (I know qBittorrent also has a nice plugin system), but I have some issues:
> 
> * I don't want to risk it getting kicked out of the Play Store
> * It would require to develop and maintain the plugins
> * It would change the app from being an interface for Real Debrid to be (also) something else -> you could use a specialized app for that, in the end it would just be a couple of taps away
> 
> So let's just say that it is in the plans ;D

Yeah thats fair :P. Well thats awesome youre thinking about it anyway. But yeah I'm not sure the best way to impliment it xD. But if you've heard of wako and helios before, then you know the other providers available ;]

**Comment by LivingWithHippos** [comment]
Man, I just tried it with Yatse, and it's really cool, it started playing immediately

**Comment by oathzed** [comment]
> Man, I just tried it with Yatse, and it's really cool, it started playing immediately

Awesome man, yeah it works great. Is it possible to make it open Yatse after you press the "open link" button?

**Comment by LivingWithHippos** [comment]
Yes! I found the docs [here](https://yatse.tv/wiki/yatse-api), I could check if yatse is installed and directly call it

**Comment by oathzed** [comment]
> Yes! I found the docs [here](https://yatse.tv/wiki/yatse-api). I could check if Yatse is installed and directly call it. I need to understand how to implement this with the buttons because the open link is useful for downloading stuff directly onto your device.

Awesome! :D. Also I noticed, VLC and Kodi aren't options to use when pressing the "open link" button. However MX player is, and it opens up mx player and plays the link perfectly.

**Comment by LivingWithHippos** [comment]
The share button is merely sharing a text containing the link with the whole system, so appearing in the list is up to them, but I can add other "open with" apps if they have APIs like the Yatse's one.

**Comment by oathzed** [comment]
> The share button is merely sharing a text containing the link with the whole system, so appearing in the list is up to them, but I can add other "open with" apps if they have APIs like the Yatse's one.

Ok that makes sense. Yeah it would be nice to have VLC and Kodi part of the open with apps

**Comment by oathzed** [comment]
> Yes! I found the docs [here](https://yatse.tv/wiki/yatse-api). I could check if Yatse is installed and directly call it. I need to understand how to implement this with the buttons because the open link is useful for downloading stuff directly onto your device.

Would you like me to open an issue for this specific problem (yatse not opening up on your phone and coming into view after pressing the "Yatse" button)

**Comment by LivingWithHippos** [comment]
Yes thanks, I need to investigate it. It may be a Yatse issue.

**Comment by oathzed** [comment]
> Yes thanks, I need to investigate it. It may be a Yatse issue.

Okay added it
