### ISSUE TITLE
[BUG] (Search) Sort by Biggest first issue 

### ISSUE THREAD

**Issue by Jm-e** [LivingWithHippos/unchained-android#240]
**Describe the bug**
When using the search function and sorting by "biggest first" the results are sorting by number of decimals not by size. 999.9mb will appear at the top and any files of 1gb or more will be under the lowest sized mb file.

**To Reproduce**
1. Go to search and search for anything 
2. Click on Sort by Bigger file first
3. Notice top is only in Mbs
4. Scroll down untill you find results with a file size of 1gb or more.

**Screenshots**
https://picbun.com/p/Kgct8u1g
As you can see sometime Mb and Gb results can also get mixed up depending on the result. 

**Smartphone:**
 - Device: Redmi note 9 pro
 - OS: Android 11

**Additional context**
- App Version: 4.40.2 beta

**Comment by Invictaz** [comment]
Very good find. Does this also occur with the other sort options?

**Comment by Jm-e** [comment]
Yeah so all are fine accept Sort by smallest and sort by biggest.

One thing to note is some providers tag file size differently.

ETree - Mb & Gb
1337x - MB & GB
Atorrents - M & G
Bitsearch - None (do not show file size at all)
ISOhunt - MB & GB
MagnetDL - MB & GB
Nyaa - MiB & GiB

Rlsbb, Scene-rls, zooqle are not showing any results.

**Comment by LivingWithHippos** [comment]
Yeah since I'm not using official apis (they don't  exists) I have to adapt what I can get from the web pages, that's why I haven't added sorting for everything. I think every sorting is made as a string and not as a number
