### ISSUE TITLE
[Request] Add a back button when on the individual link menu

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#25]
So you know that you can go back, sometimes it's confusing.

![Screenshot_20200929-124709](https://user-images.githubusercontent.com/52545913/94608446-4568c500-0252-11eb-8212-2fdc8d4cecf7.png)

**Comment by LivingWithHippos** [comment]
Thank you, I forgot that many devices do not have the physical back button.

**Comment by oathzed** [comment]
> Thank you, I forgot that many devices do not have the physical back button.

Any time

**Comment by oathzed** [comment]
Sorry I meant only add a back button to this page, it doesn't make sense to add it to every page. Since you're not under any hidden menu in the other pages, you're just going back between tabs

![Screenshot_20201002-053351](https://user-images.githubusercontent.com/52545913/94923704-209e6880-0471-11eb-9583-cb8335f34321.png)

**Comment by LivingWithHippos** [comment]
Thanks for the feedback. You are right, there are only three screens which can't be reached with the bottom bar, the download details, the torrent details, and the settings page.
Do you think it would be better to remove the back arrow on the other screens?

**Comment by oathzed** [comment]
> Thanks for the feedback. You are right, there are only three screens which can't be reached with the bottom bar, the download details, the torrent details, and the settings page.
> Do you think it would be better to remove the back arrow on the other screens?

There is a torrent details page? When I click a torrent it just takes me to the downloads section. I think you should only have a back button from the download item details page and the settings page yes

**Comment by oathzed** [comment]
Oh I found the torrent details pane. Yes so what you said, only add a back button to those 3 pages

**Comment by oathzed** [comment]
Also keep a back button here
![Screenshot_20201002-060535](https://user-images.githubusercontent.com/52545913/94926301-6c531100-0475-11eb-9545-a009dd160d1d.png)

**Comment by LivingWithHippos** [comment]
Yes that is also a download details page ;)
