### ISSUE TITLE
[BUG] Error with the translation in Weblate

### ISSUE THREAD

**Issue by edgarpatronperez** [LivingWithHippos/unchained-android#254]
Hello. I have been participating in the active translation of Unchained for android in the Spanish language. However, I did all the translation on LingoHub because I work more comfortably on that platform. I exported the data in .XML to upload it to weblate but it doesn't allow me.

Sorry if this is not the right place, I just couldn't find a way to communicate.

WEBLATE error is "Unknown filetype (unchained-for-android-strings-es.xml)"

**Comment by LivingWithHippos** [comment]
Thanks for your contribution, I saw someone translating in Spanish on Weblate! I'm not super satisfied with Weblate so I'm ready to use other platforms, as long as it's free (and possibily self hostable and open source). I 'm waiting for Mozilla Pontoon to be made easily self hostable in docker to switch to it.

> WEBLATE error is "Unknown filetype (unchained-for-android-strings-es.xml)"

XML is a generic format, probably the information in weblate xml is stored differently from the information on LingoHub xml .

I think there may be some manual work to do, at worst we can import it directly in the project skipping weblate. Would you attach the xml here so I can give it a look?

**Comment by edgarpatronperez** [comment]
Hello. At the end of my format already done in XML, I passed it to an excel format following the bases of a previous file downloaded from Weblate, I pasted my data and I just uploaded it. Apparently it already is. If you like I can send you the files

**Comment by LivingWithHippos** [comment]
Thanks I can see the translation in weblate now. I don't have time to upload it with the project right now but I'll do it this week.

Thanks again!
