### ISSUE TITLE
[BUG] New AMOLED theme, graphical bugs

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#284]
I know this is still a nightly build, but just wanted to share Incase you were unaware

**Describe the bug**
When you click certain buttons or text fields it shows them weird or removes information (maybe because it turns black when it should be white or grey)
**To Reproduce**
1. Just select any field that I've circled in the images below to see the issue

**Screenshots**
![Screenshot_20221210-093658](https://user-images.githubusercontent.com/52545913/206868139-31ea5c89-b453-4ada-be35-d3816116aa8b.png)
![Screenshot_20221210-093722](https://user-images.githubusercontent.com/52545913/206868143-8c038289-0af6-47b8-aa4a-5db00a44e009.png)
![Screenshot_20221210-093739](https://user-images.githubusercontent.com/52545913/206868144-bd46bfe8-047e-4457-9175-de5ffabefc9c.png)

**Smartphone (please complete the following information):**
 - Device: pixel 4a
 - OS: android 13

**Comment by LivingWithHippos** [comment]
Partially fixed, will be fixed with the UI rewrite #242
