### ISSUE TITLE
[BUG] Adding a repository for plugins

### ISSUE THREAD

**Issue by rockbyo5** [LivingWithHippos/unchained-android#288]
**Describe the bug**
Cannot seem to find the menu/options/method to add a repository (adding plugins via a .unchained file works just fine)

**To Reproduce**
1. Go to the plugin management menu
2. Look for a way to add a repository
3. I personally failed previous step.
Note: The "Install Plugin" button in the settings dint work either, but I'm assuming it was disabled and made to give a toast message to help guide users to the new menu.

**Smartphone (please complete the following information):**
 - Device: OnePlus  8T
 - OS: Android 12

**Additional context**
- App Version: Latest app, straight from the Github .apk (non-debug version) (4.53.2-beta)

**Comment by LivingWithHippos** [comment]
I definitely forgot to put the add repository button in the repo screen

> Note: The "Install Plugin" button in the settings dint work either, but I'm assuming it was disabled and made to give a toast message to help guide users to the new menu.

Yes it's just a description now
