### ISSUE TITLE
[BUG] Add Kodi (crash)

### ISSUE THREAD

**Issue by f1vefour** [LivingWithHippos/unchained-android#295]
**Describe the bug**
When trying to add a Kodi host it crashes to the main screen, I already have one host and have previously had two which I could choose the default between the two but I can't add a new one. I have tried clearing data and even uninstalling and reinstalling.

**To Reproduce**
Try to add Kodi host, crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 13 

**Additional context**
- App Version: 4.53.4-beta from Google Play

4.51.4-beta does not have this issue but 4.53.2-beta and later does, just checked.

Installing 4.51.4, adding the hosts, then updating to either of the two later versions it crashes when trying to switch between Kodi hosts 

It seems you added the ability to click which Kodi host one wants to use which of course is not a feature in the older 4.51.4 as clicking either host does nothing but in the later two versions it crashes just like when trying to add a host.

**Comment by LivingWithHippos** [comment]
Thanks for the report, should be already fixed, will be available on the next release. If you use the github version you can get the fixed one from github actions

**Comment by f1vefour** [comment]
Just tried version 4.53.4-beta from GitHub actions and it's the exact same way unfortunately.

**Comment by LivingWithHippos** [comment]
https://github.com/LivingWithHippos/unchained-android/actions/runs/3830157402

This one? The latest github action?

**Comment by f1vefour** [comment]
Yes that is the one.

**Comment by LivingWithHippos** [comment]
Ah right that is from the main branch. The changes are in dev so I need to trigger another action at least

**Comment by f1vefour** [comment]
I looked at dev and didn't see a difference, are there unpushed changes?

**Comment by LivingWithHippos** [comment]
May be, I remember fixing it, it's simply a wrong casting to image button of a material button

**Comment by LivingWithHippos** [comment]
https://github.com/LivingWithHippos/unchained-android/actions/runs/3984418995

I re run the github action with the latest change this should work

**Comment by f1vefour** [comment]
It indeed worked, thank you for the speedy resolution. Closing the issue.
