### ISSUE TITLE
[BUG] Keyboard stays open after text input

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#301]
After you search a keyword and click on the plug-in list the keyboard stays open. This covers all content

![Screenshot_20230226_211740_Unchained](https://user-images.githubusercontent.com/20338545/221435036-f712fa74-b393-474f-a7b9-de28df0feabc.jpg)

**Comment by Invictaz** [comment]
@LivingWithHippos 

I tested with the latest 1.2.0 dev and the bug is still there. Also when you paste the private api key in the textbox the keyboard stays open, preventing you from pressing the subtitles button.

**Comment by LivingWithHippos** [comment]
It should mostly work. Can you check if the cursor is in the text field and blinking when you expect the keyboard to be hidden?

**Comment by Invictaz** [comment]
![Screenshot_20240218_212544_Unchained-dev](https://github.com/LivingWithHippos/unchained-android/assets/20338545/b1a22750-1a16-42ca-85bb-f75b00491dbd)

Still not fixed @LivingWithHippos

**Comment by Invictaz** [comment]
Seems fixed

**Comment by LivingWithHippos** [comment]
At this point I think it's your phone :D for me the keyboard disappear pressing any dropdown or the search button either on the text field or the keyboard itself

What phone do you have? Which android version?

**Comment by Invictaz** [comment]
Samsung A33 5G Android 13

**Comment by Invictaz** [comment]
@LivingWithHippos used 1.2.1. Not fixed


https://github.com/LivingWithHippos/unchained-android/assets/20338545/ce678ed0-9ebc-4fc6-967c-427b6078ab10
