### ISSUE TITLE
Cannot send media to VLC

### ISSUE THREAD

**Issue by alecman3000** [LivingWithHippos/unchained-android#309]
I'm trying to open the link on player which is vlc and it's not opening. it's saying that vlc is not installed. but i have it installed.
![Screenshot_2023-04-25-05-08-31-439_com github livingwithhippos unchained-edit](https://user-images.githubusercontent.com/41981287/234117595-3693a9a7-a402-416e-9bc4-47e37802335b.jpg)

![Screenshot_2023-04-25-05-10-55-299_com github livingwithhippos unchained-edit](https://user-images.githubusercontent.com/41981287/234117824-2edb9074-7bc1-466a-b769-c871de8768bb.jpg)

**Comment by LivingWithHippos** [comment]
Can you check the installed vlc package name? Maybe you have the beta version or they changed the package name

**Comment by alecman3000** [comment]
> Can you check the installed vlc package name? Maybe you have the beta version or they changed the package name

![Screenshot_2023-04-26-06-18-30-841_com miui securitycenter](https://user-images.githubusercontent.com/41981287/234416583-ecaf633e-fb66-4ff8-ad93-38b4eebe2529.jpg)

Is this the package name?

**Comment by LivingWithHippos** [comment]
Yes. I can reproduce the bug so I will check on my own

**Comment by LivingWithHippos** [comment]
In the meanwhile you can use that package name as custom player and then select use custom player in the dropdown where now VLC is selected

**Comment by alecman3000** [comment]
> In the meanwhile you can use that package name as custom player and then select use custom player in the dropdown where now VLC is selected

![Screenshot_2023-04-26-15-20-52-451_com github livingwithhippos unchained-edit](https://user-images.githubusercontent.com/41981287/234500095-75ead2b7-8862-46d5-ac5c-9979be1074e1.jpg)

Alright, I tried it and it worked. I wonder why it doesn't work by default without switching yo custom player.

**Comment by LivingWithHippos** [comment]
Some apps support more features if I specifically request for them, vlc used to have one of these and it seems it does not work anymore. I will replace the custom vlc one with the default one
