### ISSUE TITLE
[FEATURE REQUEST] Send to, or play on, Vlc on PC

### ISSUE THREAD

**Issue by Mahava** [LivingWithHippos/unchained-android#310]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

Would love to play on vlc remotely, that is from android unchained to pc vlc on home network.  Or, to any other media player like media player classic, windows media player etc

Love the app.

**Describe the solution you'd like**
I want to play on vlc on my pc (or any other common media player) the same way that I can play on pc kodi with remote control.  So that would be to select a streaming link then either share or click a custom button to send to pc vlc

**Describe alternatives you've considered*
I've looked at dlna Chromecast sap http remote controls for vlc but couldn't figure out a solution. 

**Additional context**
Its super fast to send the link to vlc on my android phone where unchained is installed and begin watching but much slower to send to pc kodi because kodi has to load and finish all its tasks.  I'm hoping for a faster way to begin watching on my pc.

**Comment by Mahava** [comment]
Thatnks for the link, LWH, but im afraid im not a developer so dont have the slightest idea how to utilize these to get up to speed with playing on vlc.

i did figure out how to set up wmp but had to us another app to talk to wmp. using dnla, i think   ..wmp is a bit slow to respond though.  i was hoping to do it though unchained without another remote control app.  i vwas impressed with how quickly the link plays when sent to vlc on the same device and hoped to replicate with vlc on another device. 

btw, i read something about vlc 4  having support for dnla.   so i dowloaded the nightly and connected it to that other app but couldnt get any further than that.  i dont expect you to offer support for vlc, though.. just thought thered be a way to implemnt through unchaoned.

cheers.

**Comment by LivingWithHippos** [comment]
Ah of course, I put it there for me so I can see when I'll work on it. As for DLNA it seems it's used for streaming from a server to a client (vlc), we do not want to do that, we just want to give vlc the link and it will do everything by itself

**Comment by LivingWithHippos** [comment]
done
