### ISSUE TITLE
[FEATURE REQUEST] Add magnet hash to file information

### ISSUE THREAD

**Issue by hsp1020** [LivingWithHippos/unchained-android#311]
![Screenshot_20230517-014330](https://github.com/LivingWithHippos/unchained-android/assets/125277818/4c0703a3-b0aa-4d04-afdf-ddc458860733)

![Screenshot_20230517-014350](https://github.com/LivingWithHippos/unchained-android/assets/125277818/6dcbb0d3-2879-40b3-b9b1-526c004ce5f5)

When streaming with stremio or kodi, it is inconvenient to check magnet hash information when trying to add torrents that are not cached in real debrid to other torrent clients (ex. bittorrent, alldebrid, pikpak). need to access the real debrid site to check it. Add magnet hash to file information(Unchained).

**Comment by LivingWithHippos** [comment]
I need to check if this information is available from real debrid but it should be doable.

But I still don't understand what you want to do. The only files from unchained that are not cached are the ones from the search plugins, and you can copy the magnet from those. If you mean you have too many files selected to be played you can press on the top settings button and pick "reselect files".

**Comment by LivingWithHippos** [comment]
Why can't you add the torrent to real debrid instead of a torrent client?

**Comment by hsp1020** [comment]
Sometimes torrents that are not cached in real debrid are cached in all debrid or pikpak. at this time, need to know the hash for registering torrents in all debrid or pikpak.

**Comment by LivingWithHippos** [comment]
Thanks, I understand now

**Comment by Invictaz** [comment]
@LivingWithHippos maybe I'm blind but I don't see the hash on the torrent info screen?

![Uploading Screenshot_20240220_213501_Unchained.jpg…]()

**Comment by LivingWithHippos** [comment]
The copy and share manget buttons will let you use it
