### ISSUE TITLE
[FEATURE REQUEST] Swipe to refresh not accessible from tv

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#322]
tricks available right now to trigger an update for the download/torrent lists:
- press on a download torrent on the torrent list
- create a new download
- remove a download from the download list
- remove a torrent from the torrent list

options:

- automatic refresh with interval settable from config
- button on the button bar used for multi-selection

**Comment by Invictaz** [comment]
Maybe swipe to refresh with mouse?
