### ISSUE TITLE
[FEATURE REQUEST] Plugin to search Dodi-repacks

### ISSUE THREAD

**Issue by digitalbarrito** [LivingWithHippos/unchained-android#323]
Would be lovely, if possible, to get a plugin to search dodi-repacks in Unchained. Not sure how Github is with "spicy" links, so I won't leave a link to the official .site.

**Comment by LivingWithHippos** [comment]
It uses cloudflare so right now I don't think it's going to be possible. Maybe his repacks are on some torrent website?

**Comment by digitalbarrito** [comment]
I had a feeling Dodi's site wasn't going to be feasible but couldn't hurt to ask. I don't think dodi posts anywhere but their site and they upload the torrent file to 3rd party hosting sites like file-upload with the links to that on their site with no magnet links available, so this can probably be closed as a "Not possible"

**Comment by LivingWithHippos** [comment]
They also don't provide a direct link to torrents or magnets so even without cloudflare it wouldn't have been possible, closing
