### ISSUE TITLE
[FEATURE REQUEST] support for download Navi as download manager

### ISSUE THREAD

**Issue by fugkco** [LivingWithHippos/unchained-android#330]
**Is your feature request related to a problem? Please describe.**
The builtin download manager keeps failing. So does okhttp2. Quite often downloads fail with no way to resume, or restart, etc. There is also no real tooling around downloading files etc.

**Describe the solution you'd like**
It would be great if file downloading can be offloaded to other apps like [Download Navi](https://github.com/TachibanaGeneralLaboratories/download-navi).

**Describe alternatives you've considered**
A better download manager could be implemented in Unchained but that seems like a much bigger effort.

**Comment by Invictaz** [comment]
Does it work better than Aria2?

**Comment by fugkco** [comment]
I've never used aria2, and didn't know about it until you mentioned it. Anyway, unless you're asking for support for that too, talk about aria2 Vs Download Navi is off-topic for this issue.

**Comment by Invictaz** [comment]
Aria2 is already supported so you might want to try that first.

**Comment by LivingWithHippos** [comment]
The standard download manager is the system's own so if it's crashing you may have an issue with your phone. Anyway if you use the share button you can send the link to any downloader!

**Comment by LivingWithHippos** [comment]
> The standard download manager is the system's own so if it's crashing you may have an issue with your phone. Anyway if you use the share button you can send the link to any downloader!

I have confirmed that you can use the share button to send links to navi downloader, is there an extra feature you wanted? Anyway it's not maintained anymore and considering how google (sadly) changes the storage permissions I think it may not be compatible with newer android versions, I use aria2app on FDroid.
