### ISSUE TITLE
[FEATURE REQUEST] Search all my plugins in one go instead of selecting individually

### ISSUE THREAD

**Issue by onlytanmoy** [LivingWithHippos/unchained-android#331]
Hiya, hope you having a good Sunday :)

In the 'Search Files' section of the app, under Plugin can you please provide an option ALL which will search through all my installed Plugins for the search query?

**Comment by LivingWithHippos** [comment]
Hey thanks for the feedback! This is already in the plans with #275 so I'll be closing this as it is a duplicate. Right now I'm finishing #306 and then I'll tackle this

**Comment by onlytanmoy** [comment]
Good to know that, thanks mate 👍
