### ISSUE TITLE
[FEATURE REQUEST] Start stream when still downloading

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#337]
Is it possible to start streaming while download is still running? Aka sequential downloading or first segment downloading first?

![Screenshot_20231223_060414_Unchained](https://github.com/LivingWithHippos/unchained-android/assets/20338545/ba3d3d38-44e4-4ba3-b42d-6aa7c2d27b64)

**Comment by LivingWithHippos** [comment]
Hello, it's not possible unless real debrid adds this
