### ISSUE TITLE
[BUG] Cannot select all files in pick cache

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#338]
Pick cache screen shows no option to select all or mark all.
Second thing if all files are marked already on select files list, they should be marked in the cache tab as well?

![Screenshot_20240103_035124_Unchained](https://github.com/LivingWithHippos/unchained-android/assets/20338545/e86d50de-d026-44f7-8d2b-c926981e577e)

**Comment by LivingWithHippos** [comment]
Caches are "fixed" lists of files selected by someone else that are cached and ready to be used, you cannot modify them. I could add an option to copy the selection from the current cache to the manually selected files so you can modify them if that's what you need

**Comment by Invictaz** [comment]
I mean if there are 100 episodes cached I only want 2.

**Comment by LivingWithHippos** [comment]
You go to select files and select those 2 (right now). Caches are fixed and you cannot modify them
