### ISSUE TITLE
[BUG] Upper two buttons do the same when selecting episodes

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#340]
The upper two buttons do the same 

The / and torrent name. Either the / or the torrent name should select all episodes.
My personal preference is the torrent name to select all episodes. 

![Screenshot_20240103_041304_Unchained](https://github.com/LivingWithHippos/unchained-android/assets/20338545/ceffad09-199d-4bc5-b2ac-124b69d61c56)

**Comment by LivingWithHippos** [comment]
It's because there is a single folder on top, so selecting all the files or all the files in the top folder has the same effect. If a torrent has two main folder they will behave differently
