### ISSUE TITLE
[FEATURE REQUEST] Add solidtorrents/bitsearch plugin

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#344]
Solidtorrents and bitsearch are two search engines that are freely accessible.
I think they share most of if not all of their database

Example search query

https://bitsearch.to/search?q=1

Page 2

https://bitsearch.to/search?q=1&page=2

**Comment by LivingWithHippos** [comment]
bitsearch is already available, solidtorrent works by simply switching the link in the bitsearch plugin, I guess I could make another plugin... Looking on the net it seems they are managed by the same people anyway

**Comment by Invictaz** [comment]
I did not see that the plug-in was available under the plug-in section. My mistake.
