### ISSUE TITLE
[FEATURE REQUEST] Batch url add

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#352]
If you add 5 episodes like

https://1fichier.com/?blablabla.S01E01.mkv

https://1fichier.com/?blablabla.S01E02.mkv

https://1fichier.com/?blablabla.S01E03.mkv

https://1fichier.com/?blablabla.S01E04.mkv

https://1fichier.com/?blablabla.S01E05.mkv

It adds either only the first or the last episode.

The only way to add these is via the real-debrid website. 

From other apps I remember that multiple items would be separated by ; or , or others. This is not possible because the links are retrieved from a pastefile that shows them line by line.

**Comment by LivingWithHippos** [comment]
I think you can add them if they are separated by a newline but I need to double check

```
Link 1
Link 2
Link 3
```

**Comment by Invictaz** [comment]
I tried but that didn't work (from Samsung notes)

![Screenshot_20240123_211825_Samsung Notes](https://github.com/LivingWithHippos/unchained-android/assets/20338545/f0482380-43ae-4c60-83b8-93ff6bee2a9a)

**Comment by LivingWithHippos** [comment]
Confirmed, code for multiple links is already there, the problem is probably that the first line is recognized as a web link and then the whole list is sent as a single link.

**Comment by Invictaz** [comment]
Interesting. Is it fixable?

**Comment by LivingWithHippos** [comment]
> Interesting. Is it fixable?

yes of course the code just need to be moved and fixed a little

https://github.com/LivingWithHippos/unchained-android/blob/7bddde00fec62d5ab95337674bc03261413533d3/app/app/src/main/java/com/github/livingwithhippos/unchained/newdownload/view/NewDownloadFragment.kt#L287-L324
