### ISSUE TITLE
[FEATURE REQUEST] Rebuild logout logic

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#360]
Now logout is possible even when not logged in at all. You can press logout even when you are not logged in via api token or other method.

**Comment by LivingWithHippos** [comment]
It's the first button of the settings page, I will move it to the bottom because it has no section so it's a bit hard to spot

**Comment by Invictaz** [comment]
@LivingWithHippos I see it now. Rephrased the issue. You can press logout unlimited times, even when not logged in at all.
