### ISSUE TITLE
[BUG] DNS over https warning shown if already enabled

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#361]
The DNS over https warning and confirmation box is shown even if it is already enabled within settings

See video

https://github.com/LivingWithHippos/unchained-android/assets/20338545/13051132-6f89-4358-87ab-c4950d74d019

**Comment by LivingWithHippos** [comment]
the dialog is shown once so the user can decide what to do, it does not matter if it's alread on or off

**Comment by Invictaz** [comment]
If it is already enabled the user already made their choice anyway.
