### ISSUE TITLE
Add a delete all torrents/downloads button the bottom right

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#37]
Would be nice to bulk delete everything. Make sure to have a confirm screen.

Also when single deleting items you should have a confirm screen aswell.

**Comment by LivingWithHippos** [comment]
Confirm on delete dialogs added

**Comment by oathzed** [comment]
> Confirm on delete dialogs added

Awesome

**Comment by Invictaz** [comment]
Delete all would be welcome

**Comment by LivingWithHippos** [comment]
Closed by #97
