### ISSUE TITLE
[BUG] App crashes when deleting in-progress torrent

### ISSUE THREAD

**Issue by yellowjacketcoder** [LivingWithHippos/unchained-android#373]
**Describe the bug**
Anytime I delete a torrent that is not yet completed, the app crashes

**To Reproduce**
1. Go to Downloads > Torrents
2. Click on a torrent  that is in progress
3. In the details screen, click on trash button at the top right
4. In the confirmation dialog box, click on delete
5. See app crash alongside torrent removed toast

**Screenshots**

https://github.com/user-attachments/assets/bb49bc07-bb96-4fa3-b9df-3be91143a191

**Smartphone (please complete the following information):**
 - Device: Realme X50 Pro 5G (RMX 2076)
 - OS: Android 12/Realme UI 3.0 (F.17)

**Additional context**
- App Version: 1.2.1 (43)
Add any other context about the problem here (how often does it happens etc.).
Happens everytime I delete an in progress torrent. *Doesn't* happen when long pressing and selecting a completed torrent and then deleting it.

**Comment by LivingWithHippos** [comment]
Thanks for the report, confirmed

**Comment by LivingWithHippos** [comment]
should be fixed with 1.3.0
