### ISSUE TITLE
[?] 3.0.1 The package conflicts with an existing package

### ISSUE THREAD

**Issue by realAllonZ** [LivingWithHippos/unchained-android#384]
"Install incomplete due to conflict error"

I assume the signature has changed.

Is this to be expected?

Uninstall then reinstall?

**Comment by LivingWithHippos** [comment]
The should be 3 possible signatures:

- play store
- fdroid
- github

Did you switch from one of these since your last install?

**Comment by LivingWithHippos** [comment]
> Am I correct to asaume that GitHub will get the updates first?

yes, there's also a crude option to give a notification when an update is available, I need to remember to update it
