### ISSUE TITLE
When you go to your torrents/downloads section after adding something and refresh it starts scrolled down

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#39]
So if I add a torrent magnet and it gets downloaded,when I refresh the torrents or downloads section, the scroll bar will start scrolled down and I have to scroll up to see the newly downloaded file.

**Comment by LivingWithHippos** [comment]
ok I already know how to solve this, will fix

**Comment by oathzed** [comment]
> ok I already know how to solve this, will fix

Awesome
