### ISSUE TITLE
[BUG] The streaming button no longer works.



### ISSUE THREAD

**Issue by Telkaoss** [LivingWithHippos/unchained-android#390]
I press the "streaming" button, and the app closes without any message. I’m using Kodi, and the data is fine on my end. It was working perfectly before the update. I cleared the cache.

Google pixel 7 pro Android 14
Unchained 1.3.2

Ps: I sometimes get a message.

![Screenshot_20240912-232928.png](https://github.com/user-attachments/assets/50c65690-8c97-4f11-8210-3829ddcb6267)

**Comment by Telkaoss** [comment]
Ok, the update corrupted the data for casting...
I deleted the app data, re-entered my Kodi details, and it's working again.

Well, I lost everything, but that was the solution.

**Comment by LivingWithHippos** [comment]
Sorry about that, kodi management has been completeely reworked but I thought I had the migration ready, apparently I did not. It should not crash anyway, I'll fix it in the next version

**Comment by Telkaoss** [comment]
Okay, no problem, I will close.

One last thing, I'm trying to create a Jackett plugin to perform searches. I'm able to capture the files, but the name, size, seeders, and other details remain empty.

My regex queries seem correct to me; if you have time, could you verify them?
```

{
  "engine_version": 2.4,
  "version": 1.0,
  "url": "https://jackett:9117
  "name": "Jackett",
  "description": "Parser for Jackett",
  "author": "telkaoss",
  "supported_categories": {
    "all": "all",
    "anime": "5070",
    "software": "4059",
    "games": "1039",
    "movies": "2000",
    "music": "3000",
    "tv": "5000"
  },
  "search": {
    "category": "${url}/api/v2.0/indexers/all/results?apikey=MYAPIKEY&Query=${query}&Category[]=${category}&Page=1",
    "no_category": "${url}/api/v2.0/indexers/all/results?apikey=MYAPIKEY&Query=${query}&Page=1"
  },
  "download": {
    "internal": {
      "link": {
        "regex_use": "first",
        "regexps": [
          {
            "regex": "\"MagnetUri\":\"(magnet:[^\"]+)\"",
            "group": 1,
            "slug_type": "complete"
          },
          {
            "regex": "\"Link\":\"(https?://[^\"]+)\"",
            "group": 1,
            "slug_type": "complete"
          }
        ]
      }
    },
    "regexes": {
      "name": {
        "regex_use": "first",
        "regexps": [
          {
            "regex": "\"Title\":\"([^\"]+)\"",
            "group": 1,
            "slug_type": "complete"
          }
        ]
      },
      "seeders": {
        "regex_use": "first",
        "regexps": [
          {
            "regex": "\"Seeders\":(\\d+)",
            "group": 1,
            "slug_type": "complete"
          }
        ]
      },
      "leechers": {
        "regex_use": "first",
        "regexps": [
          {
            "regex": "\"Peers\":(\\d+)",
            "group": 1,
            "slug_type": "complete"
          }
        ]
      },
      "size": {
        "regex_use": "first",
        "regexps": [
          {
            "regex": "\"Size\":(\\d+)",
            "group": 1,
            "slug_type": "complete"
          }
        ]
      },
      "details": {
        "regex_use": "first",
        "regexps": [
          {
            "regex": "\"Details\":\"(https?://[^\"]+)\"",
            "group": 1,
            "slug_type": "complete"
          }
        ]
      }
    }
  }
}
```

**Comment by LivingWithHippos** [comment]
I'll check later, for now my suggestion is to get the result returned by jackett and paste it into https://regexr.com/ and then you can test the result of your regexes.

Jackett support will be implemented natively in the next update btw

**Comment by LivingWithHippos** [comment]
You should use `direct` instead of `internal` since that means that the plugin needs to open the link to find the information, here you do a  single call and parse only the result of the call

**Comment by Telkaoss** [comment]
Okay, thanks for the feedback, I’ll wait for the implementation of Jackett ;)
