### ISSUE TITLE
Remove cache support

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#397]
Real Debrid has removed the cache endpoint, remove the support for it

**Comment by LivingWithHippos** [comment]
Sorry I wasn't specific enough, they removed the cache "check" support, they still have the cache. They are having some troubles with the law and have implemented and are implementing some changes

https://x.com/RealDebrid/status/1859673163681960169

**Comment by Invictaz** [comment]
That tweet doesn't look too well, them being under a magnifying glass.

**Comment by Telkaoss** [comment]
Yes, it smells like the end of RD, I dream of Unchained on AD or DL

**Comment by niks4adam** [comment]
> Sorry I wasn't specific enough, they removed the cache "check" support, they still have the cache. They are having some troubles with the law and have implemented and are implementing some changes
> 
> https://x.com/RealDebrid/status/1859673163681960169

I know a lot isn't known just yet, but does this spell the end for UnchainedRD? I'm not super familiar how it all works if the cache check is gone, if the app is still able to download or if only streaming is affected at this time.

**Comment by LivingWithHippos** [comment]
The main issue isn't really the removed cache check, but the automatic filtering they'll implement which will probably stop a lot of links. The main services hit by this will be the kodi addons and Stremio, Unchained is "manual" enough

**Comment by niks4adam** [comment]
> The main issue isn't really the removed cache check, but the automatic filtering they'll implement which will probably stop a lot of links. The main services hit by this will be the kodi addons and Stremio, Unchained is "manual" enough

Ah, that makes sense. Appreciate all you do! Curious, is there currently still a way to securely over https configure the app to be able to download? I'm guessing altering these steps would still be able to download, albeit with lesser results/links?

1: Search, 2: Click on a searched result, 3: On the following page, click on the magnet link result (this is where it currently is "checking cache" and doesn't advance), 4: Pass to Downloads

**Comment by Benjamin8obadiah** [comment]
Unchained no longer functioning as it checks cache first and is stuck on checking cache now after the recent changes. Any fix?

**Comment by kaiteck** [comment]
While in checking cache page, you can just tap download all. 

It'll still work but the download selected files will not work as we cant select specific files.

**Comment by akogwapo14** [comment]
Its work only now in website of rd if you download zip file you can still get the direct video file

**Comment by LivingWithHippos** [comment]
Nevermind, seems to work now, maybe the link had issues

**Comment by LivingWithHippos** [comment]
> Still can't get past the cache check.... Will there be an app update for this?

Yeah you need to update of course ;D I'm publishing it now (not on the play store yet)

**Comment by LivingWithHippos** [comment]
Update published

**Comment by akogwapo14** [comment]
Thank you sir
