### ISSUE TITLE
Torrent section completed circle things disapear

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#40]
Ok so if you go to the torrent section with all downloaded items, then scroll down and back up the circles will disapear if they go off screen

**Comment by LivingWithHippos** [comment]
I can see this happening, it's a little strange because it's just a value read from the JSON returned, like the title in the card view... Will check.

**Comment by oathzed** [comment]
> I can see this happening, it's a little strange because it's just a value read from the JSON returned, like the title in the card view... Will check.

Ahh gotcha, thanks man

**Comment by LivingWithHippos** [comment]
Since the circle thing was a progress bar, it didn't have much sense to show it for completed torrents. I removed it since it probably slowed the scroll operations and gave issues like this.

**Comment by oathzed** [comment]
> Since the circle thing was a progress bar, it didn't have much sense to show it for completed torrents. I removed it since it probably slowed the scroll operations and gave issues like this.

Makes sense. Smart idea
