### ISSUE TITLE
Delete and share items somehow get stuck on the new downloads page

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#41]
![Screenshot_20201002-062919~2](https://user-images.githubusercontent.com/52545913/94928611-cef9dc00-0478-11eb-8b41-14c3180d6c64.png)

**Comment by LivingWithHippos** [comment]
Mmmh I can't reproduce this. Can you try to write down your steps to reach this next time it happens?
Something like:
1. new download page -> added link -> pressed unrestrict
2. download details page -> pressed back from the top button

**Comment by oathzed** [comment]
> Mmmh I can't reproduce this. Can you try to write down your steps to reach this next time it happens?
> Something like:
> 
> 1. new download page -> added link -> pressed unrestrict
> 2. download details page -> pressed back from the top button

Restart the app, go to lists tab, open a downloaded item, press New download tab, then you'll see result

**Comment by LivingWithHippos** [comment]
Thanks, nice catch

**Comment by oathzed** [comment]
> Thanks, nice catch

No problem
