### ISSUE TITLE
Downloading a link

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#45]
So when i add a magnet lnk, i press unrestrict, then it goes to the screen where it says its downloaded, so i press the download button, this goes back to the "New download" tab and inserts the real-debrid link of what i added to unrestrict, it also looks like it presses down the "unrestrict" button without me touching it, but thats all it does. So i press the unrestrict button and it takes me to the finished screen where i can open link/copy link etc.

Is it supposed to launch this page by itself? or are you supposed to press the unrestrict button yourself? either way theres a bug where it presses down the button itself (it looks like its in pressed state)

**Comment by LivingWithHippos** [comment]
It is supposed to click the button by itself

**Comment by oathzed** [comment]
> It is supposed to click the button by itself

Ok, yeah so then it doesn't complete the action

**Comment by LivingWithHippos** [comment]
The download button from the torrent details page now points directly to the download details page. 5b346f4010c175f897fe0a2dbff55618a32ddd57
