### ISSUE TITLE
Delete/remove button

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#46]
![Screenshot_20201002-125648~2](https://user-images.githubusercontent.com/52545913/94964698-fff50380-04ae-11eb-9d25-1408a2e5d408.png)
![Screenshot_20201002-125700~2](https://user-images.githubusercontent.com/52545913/94964713-071c1180-04af-11eb-8a01-c85b6171d65a.png)

You should make them the same, either both remove or delete so it's consistent :p

**Comment by LivingWithHippos** [comment]
You're right, I started with deleted and moved to removed, will fix
