### ISSUE TITLE
Premium day count off by a day?

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#48]
On RD website it says i have 205 days, on Unchained it says 204 days

**Comment by LivingWithHippos** [comment]
It's probably just a rounding difference. The api returns the number of seconds of premium and I divide them by 60 seconds, 60 minutes, and 24 hours to get the number, so if you have 204 days and 23 hours Unchained shows it as 204 days. RD probably rounds it up to 205.

**Comment by oathzed** [comment]
> It's probably just a rounding difference. The api returns the number of seconds of premium and I divide them by 60 seconds, 60 minutes, and 24 hours to get the number, so if you have 204 days and 23 hours Unchained shows it as 204 days. RD probably rounds it up to 205.

Ok I got yeh, makes sense
