### ISSUE TITLE
Integration with kodi

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#58]
Add an option in the settings with a login for Kodi (IP, port, username, password) with a button to auto-detect, and its [APIs](https://kodi.wiki/view/JSON-RPC_API) to send streams to it. See [Kore](https://github.com/xbmc/Kore/blob/213374b6a67c24de49e7d91269d4f051804153f2/app/src/main/java/org/xbmc/kore/ui/sections/hosts/AddHostActivity.java) for code examples

**Comment by oathzed** [comment]
To add to this, will you be adding a remote when it starts playing?

Check kodi's open source remote, Kore as a possible option to get some code from: https://github.com/xbmc/Kore

**Comment by LivingWithHippos** [comment]
I'm not sure about the remote; it would start moving away from the main app functionality a little too much. I think it would be better to leave the remote feature to a specialized app such as Kore. Maybe in the future...

**Comment by oathzed** [comment]
> I'm not sure about the remote; it would start moving away from the main app functionality a little too much. I think it would be better to leave the remote feature to a specialized app such as Kore. Maybe in the future...

True, makes sense

**Comment by Invictaz** [comment]
I would leave this to Kore and/or Yatse. They also have subtitle searching etc built in.
