### ISSUE TITLE
Make Yatse open up and come to the foreground of your phone screen after pressing "Yatse" button

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#66]
Refer to this: https://github.com/LivingWithHippos/unchained-android/issues/24#issuecomment-702747465

**Comment by LivingWithHippos** [comment]
So, the list of possible actions is in the [api page.](https://yatse.tv/wiki/yatse-api) The only command that can receive a link is the one already implemented. It will start playing from the last selected device in Yatse. 

What are you looking for? Start the link and then bring the app to the front?

Maybe after the queueing of the link I could add another call to org.leetzone.android.yatsewidget.ACTION_APP_SHOW_HOME

**Comment by oathzed** [comment]
> So, the list of possible actions is in the [api page.](https://yatse.tv/wiki/yatse-api) The only command that can receive a link is the one already implemented. It will start playing from the last selected device in Yatse.
> 
> What are you looking for? Start the link and then bring the app to the front?
> 
> Maybe after the queueing of the link I could add another call to org.leetzone.android.yatsewidget.ACTION_APP_SHOW_HOME

Yeah exactly that. Hopefully that'll work

**Comment by Invictaz** [comment]
For me, the Yatse buttons now do not work at all. Is this issue known?

**Comment by LivingWithHippos** [comment]
I took a look at it and it seems that aside from some api changes since last year the play uri action we need is locked behind the pro version. I'm not particularly keen on implementing it since it's neither open source nor free. I'll remove it and replace it with direct share to kodi when I have the time

**Comment by Invictaz** [comment]
AFAIK Kore is free. It's the official Kodi remote and in my tests it's even faster than Yatse. To be honest I do not really get the hype behind Yatse.

**Comment by LivingWithHippos** [comment]
closed by #106
