### ISSUE TITLE
Shared links flagged as unsupported.

### ISSUE THREAD

**Issue by Cueball666uk** [LivingWithHippos/unchained-android#70]
I have noticed that if I send a hosted link to Unchained and Real-Debrid supports it, then I will be presented with appropriate links to download. I would really appreciate having some sort of popup telling me if a hosted link was not supported.

Amazing work with the integration of Yatse. Your app is awesome. 🙂👍🏻

**Comment by LivingWithHippos** [comment]
> Amazing work with the integration of Yatse. Your app is awesome. 🙂👍🏻

Thanks, man B)

**Comment by LivingWithHippos** [comment]
closed with 71cfaf55197c4534fefc51221279df5a8c6b79b1
