### ISSUE TITLE
Add a download button

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#75]
Add to the download fragment a download button, replacing the open link one (you can already use the share button instead).

Since the download manager is already implemented to open torrent links it should be pretty easy. 

I  avoided adding an internal downloader because a dedicated download manager (such as aria2app) will always be better but for small files it's probably enough. Will also need to check API compatibility.

**Comment by Invictaz** [comment]
Do you mean download to Realdebrid or to phone?

**Comment by LivingWithHippos** [comment]
To the phone. To "download" to real debrid you just use the new download menu

**Comment by Invictaz** [comment]
There is no download to phone button if the episode torrent is already downloaded to Realdebrid. 
![Screenshot_20210523-171618_Unchained](https://user-images.githubusercontent.com/20338545/119266245-450aa900-bbea-11eb-9ab2-27411c14bbd0.jpg)

**Comment by LivingWithHippos** [comment]
The download link is simply the one   used by the share or open buttons. Pass it to your favorite browser or even better to a dedicated download manager like [aria2app](https://play.google.com/store/apps/details?id=com.gianlu.aria2app ) (my personal favorite)

**Comment by Invictaz** [comment]
It's quite confusing that Unchained says "download" and that you need an external download app to download to your phone. 

However I do understand that developing an internal downloader is like reinventing the wheel. 

Maybe downloading to Realdebrid should be called "importing to cloud" or something.

**Comment by LivingWithHippos** [comment]
Actually Android provides a download manager so I was going to use that. I use the word "download" because that is what real debrid uses in the documentation. After the next big update (torrent search) I'll start adding smaller stuff like this.

**Comment by Invictaz** [comment]
But why implement a torrent search engine? There are very good apps for that?

**Comment by LivingWithHippos** [comment]
Different people have different needs/flows and ask me to implement them. I personally have never used dlc containers, don't need torrent search engines because I use them directly (like you said), don't need the app to run on the fire tv because I send my links to it with a remote app and don't need an internal download because I use specialized app such as aria2android ;D

**Comment by Invictaz** [comment]
Well DLC containers are used quite a lot in filehosters that are compatible with Realdebrid. 

Btw, Aria2app doesnt support DLC containers as well.
