### ISSUE TITLE
Compatibility with tv devices such as the fire tv

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#77]
Right now the app is working, but it has some issues:

- [x] TextInput fields not focusable
- [ ] hard to see which field/button is currently selected (temporary workaround: try the other themes, tropical and black and white night version seem to be a little better)
- [ ] simplify layout?
- [ ] magnet link won't show an app chooser (at least on firefox for fire tv), check different browsers and also torrent files
- [ ] switch the open link button in the download fragment with the share button. The latter allows the user to choose players like vlc while the former does not

Some of these may be linked to #76 

It is also possible that the app needs to be [updated for android tv itself ](https://developer.android.com/training/tv/start)

[Check all these issues about android tv before opening a new one](https://github.com/LivingWithHippos/unchained-android/issues?q=is%3Aopen+is%3Aissue+label%3Atv)

**Comment by Bahnzo** [comment]
Thanks for the update, I'll give this a try later and let you know if there's any issues.

**Comment by byrek3d** [comment]
Would it also be possible to add a sort by ascending/descending option? On the TV it gets really hard to have to find an episode if the torrent contains many files.
What would be ideal for me would be a way to remember what was the last file opened from a torrent, that way I can just select the next one on the list.

**Comment by LivingWithHippos** [comment]
So, the main issue is that this app wasn't made for the android tv, my use case for the tv was installing it on a phone and send links to the android tv with a remote app like kore and such. The UI is also not optimized for the android tv, a lot the UI code would need to be re-written so I don' t know when I'll have the time. 

> Would it also be possible to add a sort by ascending/descending option? 

It would be complicated because the real debrid api return results from the last generated link sorted by date, as I said it would be much easier to use the search function on the phone.

> What would be ideal for me would be a way to remember what was the last file opened from a torrent, that way I can just select the next one on the list.

It could help if I implemented #31 so follow that.

A super cool feature would be to make an integration with imdb and link episodes/movies with files.
