### ISSUE TITLE
Copy/Paste on Fire TV app doesn't work. 

### ISSUE THREAD

**Issue by Bahnzo** [LivingWithHippos/unchained-android#78]
Ok, so the next issue, is trying to copy/paste the API key into the app for some reason only pastes the final character of the key into the field. 

I use (I think it's an official app) a FireTV app on my Android to interface with the FireTV when something like this is needed. It's too difficult to manually type something like this API key into apps, so using this app to paste these things into various apps on the FireTV has always been the solution. I've never seen this happen before, but I can assure you it's never been an issue with with others, so it must somehow be localized to your Unchained app. 

Maybe the real answer here, is to implement a true device authorization from/to real-debrid? I think I read you are doing this to learn programming android? So no real hurry, I'm able to use Kodi to access R-D, but I'd love to have a standalone program that does it, and I'm happy to help you out with a little troubleshooting.

**Comment by LivingWithHippos** [comment]
I had this problem too, before pasting you have to open the on-screen keyboard, you can't paste directly into the field. Just tap on the input field once or twice. I'll try to make the paste option appear anyway.

**Comment by Bahnzo** [comment]
Ok that works, but I guess I'm confused here, because the whole point was I want to stream a file directly from R-D and I don't see how that's possible in the app. 

If I choose the file, and then select "Open Link" it wants to open Firefox. In which case that's not making any sense, as I'd just open Firefox anyways and log in to R-D and bypass the app altogether. "Load Stream Links" Just pops up some options which don't seem to be selectable and don't play the video either. 

Am I missing something here?

**Comment by LivingWithHippos** [comment]
Use the share button on top right and open it with vlc or another player. I'll change something to make it easier in the future

**Comment by LivingWithHippos** [comment]
closed with new buttons layout. Other tv issue can be tracked in #77
