### ISSUE TITLE
Orionoid Integration

### ISSUE THREAD

**Issue by JeremyNichvalodoff** [LivingWithHippos/unchained-android#85]
Hi spoke to the team and Orionoid, They have your app listed as an app that works with them but said I should contact you to see how the integration works.

**Comment by LivingWithHippos** [comment]
Hey, thanks for reaching out. Oriondroid still has not be implemented. I tought there was already an issue opened for this or a generic torrent search function but i guess I was wrong, so I will post updates here. There's already a branch but it's outdated and needs to be redone. 

By the way, just to be sure, this app is to be used in conjunction with Real Debrid, not as a torrent search app.

**Comment by Invictaz** [comment]
If we add Orionoid, the next step will be adding scrapers like Openscrapers or something. But that's not really the goal of this app.

**Comment by LivingWithHippos** [comment]
On hold while testing the search plugins

**Comment by LivingWithHippos** [comment]
seeing as the scrapers are working "good" I'm closing this issue at the moment. May be reopened if I decide to re add it
