### ISSUE TITLE
VLC doesn't appear in the "Open With" list

### ISSUE THREAD

**Issue by renatopdalencar** [LivingWithHippos/unchained-android#87]
Hi! As the title says, I can't get VLC to appear as an "Open With" option. If I install MX Player Pro, it is shown there. So I wonder what is the problem with VLC. I personally prefer VLC because the audio volume goes way louder.
![Screenshot_20210325-204719](https://user-images.githubusercontent.com/65918656/112558789-58e28c00-8dae-11eb-8c6d-def28e5b7063.jpg)

**Comment by LivingWithHippos** [comment]
It's just the way "open with" works. You can use the share option to get vlc I think. Since this is not the first report about this I think I'll add an option to exchange open with with the share button.

**Comment by renatopdalencar** [comment]
> It's just the way "open with" works. You can use the share option to get vlc I think.

Wow, you're right! If I press share, I get the "play with VLC" option. 

> Since this is not the first report about this I think I'll add an option to exchange open with with the share button.

That would be just perfect. Thank you very much!

**Comment by LivingWithHippos** [comment]
Added the share button to the buttons list thanks to #99
