### ISSUE TITLE
[Feature suggestions] Open stream in browser

### ISSUE THREAD

**Issue by DaedalusBLN** [LivingWithHippos/unchained-android#89]
RD offers a web player at https://real-debrid.com/streaming-????????????? (I think 13 digits) for videos. A "Stream in browser" option would be highly appreciated. I know that you offer the "Load stream links" option but it is not the same.

Another cool feature would be to display multifile cached torrents (season packs/batch packs) as 'folders' and sort the files within alphabetically by filename so we can view downloads in groups and easily select the right file.

**Comment by LivingWithHippos** [comment]
> RD offers a web player at https://real-debrid.com/streaming-????????????? (I think 13 digits) for videos. A "Stream in browser" option would be highly appreciated. I know that you offer the "Load stream links" option but it is not the same.

This should be doable, it's undocumented but it just appends the file id of a streamable file to that link.

> Another cool feature would be to display multifile cached torrents (season packs/batch packs) as 'folders' and sort the files within alphabetically by filename so we can view downloads in groups and easily select the right file.

This is more complicated, anyway you can follow this issue: #31 and maybe I' ll open an issue to let people select files from torrents (right now it's all or nothing)

**Comment by DaedalusBLN** [comment]
I can confirm that it is the file ID. As there are certain devices where I am pretty much stuck with streaming through the browser (a certain VR headset) this feature would be very much appreciated. As for the 'folder' listing a sorting there are open source projects that do this, one is the Kodi add-on called Seren by nixgates, another one is an add-on called Helios for a closed-source application called wako. Maybe looking at that code would be helpful?

But that's just a convenience feature. The 'stream in browser' feature should be much easier to add and it would be a game changer :) The webplayer is even able to open video files with multiple audio and subtitle streams and lets you pick a track. Pretty darn useful and performs quite well.

**Comment by DaedalusBLN** [comment]
I'm just thinking out loud here... Since this is an undocumented API function what is the difficult part? To check whether the file in question is a video file which the web-player offers to stream? Thanks for looking into this. This feature is mostly useful for the rare cases where a video player is not a good option. On Facebook's Oculus Android Platform, one is able to sideload Android applications but they display inside a virtual screen with low resolution, limited to 1280x720 while the device has a total resolution of 1832×1920 per eye. But VR applications such as Oculus's Web Browser and Firefox Reality browser are not subject to the limitations of the regular android applications. Furthermore, to my knowledge, there is no video player VR application for the Oculus Android platform able to handle streaming links or intents of any kind so I'm kinda stuck using a browser for RD stuff. Which is totally fine... I am just looking for convenience hacks at the moment, and a feature to launch the browser from inside Unchained would be precisely what I need :) Thanks once again for looking into it and take your time.

**Comment by LivingWithHippos** [comment]
> To check whether the file in question is a video file which the web-player offers to stream?

we already have this feature luckily

Can you test this apk? It´s based on branch [browser-stream](https://github.com/LivingWithHippos/unchained-android/tree/browser-stream) and works fine on my phone but I´d like some feedback.

Unzip and install [browser-stream-test.zip](https://github.com/LivingWithHippos/unchained-android/files/6312458/unchained-browser-stream-test.zip)

**Comment by DaedalusBLN** [comment]
@LivingWithHippos Works flawlessly. Checked on my phone and will be sideloading it on the Oculus Quest 2 later tonight. Had to uninstall the Play Store version before I got this to successfully install, but it works flawlessly. Thanks a bunch for adding this feature. Much appreciated.

**Comment by LivingWithHippos** [comment]
> Had to uninstall the Play Store version before I got this to successfully install

it´s because the Play Store uses its own signing keys and you can´t overwrite the same app with a different signature. I use my own signature on Github and in the future for F Droid too, I think.

Closed by #91
