### ISSUE TITLE
[Feature request] Option to download video link as ".m3u" file

### ISSUE THREAD

**Issue by Mav3r1x** [LivingWithHippos/unchained-android#90]
Some of the video players do not appear in the share menu. If you can offer an option to download the mp4/mkv/xxx url link as an ".m3u" file, we can open it with any video player. And even copy the file to other devices and open there as well.

**Comment by LivingWithHippos** [comment]
Hey man thanks for the feedback. Sadly most of these things are manage by real debrid and I cant change those. Maybe I could add an option to download the files provided by transcoding. Have you checked the transcoding options by the way? You need to log in with the private api key and then for video files you get an option for loading media. Some of those are streaming options and not direct downloads. Btw sharing links there's risks of your account getting banned by real debrid so be careful

**Comment by LivingWithHippos** [comment]
> sharing links brings risks of your account getting banned by real debrid so be careful

Note: I'm not actually sure of this.

Anyway you can try with both the open and share menu to see all the available apps. Also the "load media" button will give you an m3u8/mpd/mp4/webm option which should be supported by almost every player
