### ISSUE TITLE
Add MEGA folder support

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#92]
Right now adding a folder from MEGA gives 

"Unsupported hoster"

Error.
However if I add the folder on the real debrid website all the files in the folder are parsed and added to the Unchained app. Even the non mkv and non mp4 files. So hard to digest which are what. Maybe filter those out?

Point is that this app does not like MEGA folders. 

Adding individual MEGA files with their respective urls from that same folder works strangely enough.

**Comment by LivingWithHippos** [comment]
Thanks for the report, I've found the bug.

Folders link needs to be sent to the `unrestrict/folder` endpoint and not the `unrestrict/link` endpoint. To fix this I need to:

- [ ] implement the folder endpoint with retrofit etc.
- [ ] create a list of regexs to recognize the folder links
- [ ] connect everything

It shouldn't be too hard

**Comment by LivingWithHippos** [comment]
Closed with the latest commit set, from 8abfee70ac2bdd6ff70bd1e32fb76f9bd8456816 to 74d6a101a8fa00d8aacdb095a6b7b09257377935

Had to create a new folder fragment which is also useful for #31

**Comment by Invictaz** [comment]
Thanks a lot for the very fast response and fix. Going to test it as a new release is out :)

**Comment by LivingWithHippos** [comment]
> 
> 
> Thanks a lot for the very fast response and fix. Going to test it as a new release is out :)


In the meanwhile you can preview it on the [latest build](https://app.circleci.com/pipelines/github/LivingWithHippos/unchained-android/745/workflows/1ee364c6-1e74-4007-8fb4-35a667eb9240/jobs/739/artifacts)
