### ISSUE TITLE
Add containers support

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#95]
Filehosters group the individual parts of a file into .dlc files. Comparable to .nzb

Currently it's not implemented. Not sure if it's only the extension that needs support or more work. 

.dlc files may have some sort of encryption?

**Comment by LivingWithHippos** [comment]
Real Debrid currently supports RSDF, CCF, CCF3 and DLC containers. It should not be too hard to add.

**Comment by Invictaz** [comment]
When importing containers, they are opened or first downloaded like torrents?

When downloaded, this takes an extra step to download it to phone afterwards via aria2app. 

Hopefully we can avond the extra steps and use realdebrid to unlock the filehost and download to device. This is the same behavior as Jdownloader2 does on pc.

**Comment by LivingWithHippos** [comment]
I have never used a container so I'll need to find one and test it with real debrid. As a general rule, it will work like when you load them into real debrid.

They should be links to hosted files, right? Then they should be ready for use. I'll probably throw them into the new folder screen.

**Comment by Invictaz** [comment]
Yes but maybe they contain encrypted content. Not sure.
