### ISSUE TITLE
App crashes if Real Debrid is into maintenance mode

### ISSUE THREAD

**Issue by mdv0** [LivingWithHippos/unchained-android#98]
Real debrid app started crashing from yesterday. Now when ever i open the app it closes itself. before it was working fine for about a month or so, have tried both the latest build and the old one both closes itself. smartphone mi 11 lite running on android 11 and Miui 12.0.11

**Comment by Cueball666uk** [comment]
This happens when RD are having issues.

**Comment by LivingWithHippos** [comment]
Yes yesterday around 1 pm real debrid went into maintenance mode. I'd still like to avoid the app crash but mine was not crashing, maybe because I already had it opened or because I was using the api key. @mdv0 how did you log in to Unchained? Private api key or with the token flow?

**Comment by mdv0** [comment]
> Yes yesterday around 1 pm real debrid went into maintenance mode. I'd still like to avoid the app crash but mine was not crashing, maybe because I already had it opened or because I was using the api key. @mdv0 how did you log in to Unchained? Private api key or with the token flow?

Its working now and crash was definitely due to maintaince being carried out by RD. yes i logged in via api key.

**Comment by LivingWithHippos** [comment]
We can keep this open since I'd like to avoid a crash just because the site is down

**Comment by LivingWithHippos** [comment]
Should've been fixed by fad8f53746f787a095e88f51ffa4a672249af397
